// deno-coverage-ignore-file
/**
 * This file is autogenerated by a build or script process.
 * It has not been manually modified and should not be altered directly.
 * Any changes to the generated content should be made through the
 * corresponding source files or template configurations.
 */
import Handlebars from "handlebars/runtime.js";
import TemplateDataSchema from './schema.ts'

const compiled = Handlebars.template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = ((helper = (helper = lookupProperty(helpers,"content") || (depth0 != null ? lookupProperty(depth0,"content") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : (container.nullContext || {}),{"name":"content","hash":{},"data":data,"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":13}}}) : helper))) != null ? stack1 : "")
    + "\n";
},"useData":true});

export default function(context) {
  try{
    const data = TemplateDataSchema.parse(context);
    data.styles.css = `\n/* Intentionally empty: WhatsApp messages are plain text. This file exists only because
   compiler.ts always reads a sibling styles.css for every .hbs it compiles. */
` + '\n' + data.styles.css
    return compiled(data);
  } catch (e) {
    throw new Error(e.message)
  }
}

// Raw source, for database-sync seeding — see `db/manifest.ts`.
export const source = "{{{content}}}\n";
export const styles = "/* Intentionally empty: WhatsApp messages are plain text. This file exists only because\n   compiler.ts always reads a sibling styles.css for every .hbs it compiles. */\n";
    