// deno-coverage-ignore-file
/**
 * This file is autogenerated by `deno task build-handlebars` (see `handlebars/compiler.ts`).
 * It has not been manually modified and should not be altered directly — add a new base
 * template's `.hbs`/`schema.ts`/`styles.css` under `handlebars/{channel}/{name}/` and rerun
 * the build task instead (see `docs/templates.md`'s "Adding a custom template" section).
 */
import type { Notifiers } from 'typings/general.ts'

/**
 * The full list of `{channel, name}` pairs that own a real `.hbs` file in source
 * (`handlebars/{channel}/{name}/`) — the only templates a database sync can seed from or resync
 * against. Discovered directly from which `main.hbs` files exist, not maintained by hand.
 */
export const CODE_TEMPLATES: ReadonlyArray<
  { channel: Notifiers; name: string }
> = [
  { channel: 'email', name: 'generic' },
  { channel: 'sms', name: 'generic' },
  { channel: 'whatsapp', name: 'generic' },
]
