import type { Model } from '@zanix/datamaster'
import type { Notifiers } from 'typings/general.ts'
import type { ZanixTemplateAttrs } from 'typings/templates-db.ts'
import type { DerivedTemplateDeclaration } from 'typings/templates.ts'

import { derivedTemplates as smsDerivedTemplates } from '../transactional/sms.ts'
import { derivedTemplates as whatsappDerivedTemplates } from '../transactional/whatsapp.ts'
import { derivedTemplates as emailDerivedTemplates } from '../transactional/email/auth.ts'
import { CODE_TEMPLATES } from './code-templates.generated.ts'

/**
 * The full list of `{channel, name}` pairs that own a real `.hbs` file in source
 * (`handlebars/{channel}/{name}/`) — the only templates a database sync can seed from or resync
 * against. Transactional wrapper templates that share another template's `.hbs` under different
 * default data (e.g. email's `welcome`/`password-changed`/`password-recovery`/`login-otp`, all of
 * which render `email/generic`) are intentionally NOT listed here — they have no `.hbs` of their
 * own to sync (see `DERIVED_TEMPLATES` below instead).
 *
 * Generated by `deno task build-handlebars` (see `handlebars/compiler.ts`) straight from which
 * `main.hbs` files exist — re-exported here rather than declared by hand, so adding a new base
 * template only ever needs the build task rerun, never a separate registration in this file too.
 */
export { CODE_TEMPLATES }

/** A code-defined template's identity plus its compiled artifacts, as read from its `main.js`. */
export interface CodeTemplateEntry {
  channel: Notifiers
  name: string
  hbs: string
  styles: string
}

/**
 * Every declared "derived" template (see `typings/templates.ts`'s `DerivedTemplateDeclaration`) —
 * one that renders through another template's `.hbs` under different default/transformed data
 * (e.g. `welcome` renders `email/generic`) rather than owning one of its own — the complement to
 * {@link CODE_TEMPLATES}.
 *
 * Aggregated here from each channel's own `transactional/*` module (`derivedTemplates`), which is
 * the ONLY place a new derived template needs to be declared — this array (structural
 * `{channel, name, parent}`, read by `LocalTemplateBackend`'s seeding) and `TemplateProvider`'s
 * transform lookup (read by `resolve()`'s chain walk) both derive from the very same declarations,
 * so nothing needs registering twice in two different files.
 *
 * Each one is seeded, once, as a content-less "fallback" record (`hbs` absent, `parent` set,
 * `source: 'database'` — see `LocalTemplateBackend`'s sync) so `TemplateProvider.resolve()`'s
 * database path (not just the code path) can find it and walk to `parent`'s live content — see
 * `docs/templates.md#template-inheritance`. Once an admin gives one of these records real content
 * of its own directly in the database, it behaves exactly like any other independent record from
 * then on, `parent` or not.
 *
 * `name` here is the exact `zanixTemplate` string (the transactional registry's own key, e.g.
 * `'password-changed'`, not the JS function name `passwordChanged` — see
 * `transactional/email/mod.ts`), since that's what a lookup is actually keyed on.
 */
export const DERIVED_TEMPLATES: ReadonlyArray<DerivedTemplateDeclaration> = [
  ...smsDerivedTemplates,
  ...whatsappDerivedTemplates,
  ...emailDerivedTemplates,
]

/**
 * Loads every entry in {@link CODE_TEMPLATES} from its compiled `main.js` (the `source`/`styles`
 * exports `compiler.ts` embeds at build time — see `handlebars/compiler.ts`).
 */
export async function loadCodeTemplates(): Promise<CodeTemplateEntry[]> {
  return await Promise.all(
    CODE_TEMPLATES.map(async ({ channel, name }) => {
      const { source, styles } = await import(
        `../handlebars/${channel}/${name}/main.js`
      )
      return { channel, name, hbs: source as string, styles: styles as string }
    }),
  )
}

/** Hashes `text` (SHA-256, hex-encoded) — used for `ZanixTemplate.hash`/`lastSyncedHash`. */
export async function hashContent(text: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(text),
  )
  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join(
    '',
  )
}

/** Mongo's duplicate-key error code — see `seedMissingDerivedTemplates`/`syncCodeTemplates`'s own concurrent-seed handling. */
export const DUPLICATE_KEY_ERROR_CODE = 11000

/** Whether `error` is a Mongo duplicate-key failure (a unique-index violation), as opposed to any other write failure. */
export function isDuplicateKeyError(error: unknown): boolean {
  return typeof error === 'object' && error !== null &&
    (error as { code?: unknown }).code === DUPLICATE_KEY_ERROR_CODE
}

/**
 * Seeds a content-less "fallback" record (`hbs` absent, `parent` set, `source: 'database'` — see
 * {@link DERIVED_TEMPLATES}'s own doc comment) for every declared derived template not already
 * present in `existingKeys`. Shared by both sync paths that seed this collection's defaults —
 * `LocalTemplateBackend`'s same-process sync and `TemplatesAdminRepository.syncCodeTemplates`'s
 * remote/cross-service sync — since {@link DERIVED_TEMPLATES} is a fixed list this package alone
 * declares (never app-configurable), the caller never needs to pull it from anywhere; it only needs
 * to know what already exists so it doesn't insert a duplicate or clobber content an admin already
 * gave one of these records directly (see `docs/templates.md#template-inheritance`).
 *
 * Each entry is a single atomic `updateOne({channel,name}, {$setOnInsert: ...}, {upsert: true})` —
 * same reasoning as `syncCodeTemplates`'s own `toSeed` step: safe to call concurrently from N
 * replicas racing the exact same not-yet-seeded derived template, since only the replica whose
 * result carries `upsertedCount: 1` counts it as newly seeded; the other either no-ops onto the
 * same row or hits the collection's unique `{channel,name}` index as a duplicate-key error, caught
 * here and treated as "already seeded," never surfaced as a failure.
 *
 * @param existingKeys `` `${channel}:${name}` `` keys already present in the collection, for ANY
 * `source` — a derived name that already has its own record (fallback or promoted-to-real-content)
 * must never be re-inserted.
 * @param updatedBy Actor stamped on every inserted row.
 * @returns How many derived templates were actually, newly seeded (0 if all already existed).
 */
export async function seedMissingDerivedTemplates(
  Model: Model<ZanixTemplateAttrs>,
  existingKeys: ReadonlySet<string>,
  updatedBy: string,
): Promise<number> {
  const missing = DERIVED_TEMPLATES.filter(
    (entry) => !existingKeys.has(`${entry.channel}:${entry.name}`),
  )
  if (!missing.length) return 0

  // A fallback record has no `hbs` to hash, but `hash` itself is `required` — any non-empty,
  // stable placeholder works (see `docs/templates.md#name-vs-hash`: `hash` only needs to change
  // whenever `hbs` does, and an absent `hbs` never does).
  const noContentHash = await hashContent('')
  const now = new Date()

  const seededFlags = await Promise.all(
    missing.map(async (entry) => {
      try {
        const { upsertedCount } = await Model.updateOne(
          { channel: entry.channel, name: entry.name },
          {
            $setOnInsert: {
              channel: entry.channel,
              name: entry.name,
              parent: entry.parent,
              // Not `source: 'code'` — there's no `.hbs` in code to keep this in sync against,
              // so it's database-owned from the moment it exists, exactly like any other record
              // with no code counterpart.
              source: 'database',
              active: true,
              version: 1,
              hash: noContentHash,
              lastSyncedAt: now,
              updatedBy,
            },
          },
          { upsert: true },
        )
        return Boolean(upsertedCount)
      } catch (error) {
        if (!isDuplicateKeyError(error)) throw error
        return false
      }
    }),
  )
  return seededFlags.filter(Boolean).length
}

/**
 * Cache of already-resolved db template lookups, keyed by `` `znx:${channel}:${name}` ``.
 *
 * Populated wholesale via `resetPreloadedDBTemplates()` — once per one-time-worker invocation,
 * from the map `NotifierProvider.onDestroy()` preloaded on the main thread (see
 * `providers/notifier.ts`) — rather than filled incrementally per key, so `LocalTemplateBackend`'s
 * own module graph (a fresh one per worker) only ever holds the entries relevant to that one
 * invocation.
 */
let preloadedDBTemplates = new Map<
  `znx:${Notifiers}:${string}`,
  ZanixTemplateAttrs | undefined
>()

/**
 * Returns the shared cache of preloaded db template lookups.
 */
export const getPreloadedDBTemplates = (): Map<
  `znx:${Notifiers}:${string}`,
  ZanixTemplateAttrs | undefined
> => {
  return preloadedDBTemplates
}

/**
 * Replaces the shared cache with the provided map — called once per one-time-worker invocation
 * (see `sendBackgroundMessage()`) to hydrate this worker's own cache, and in tests to reset state
 * between cases.
 *
 * @param values The map to use as the new shared cache. Defaults to an empty map.
 */
export const resetPreloadedDBTemplates = (
  values = new Map<
    `znx:${Notifiers}:${string}`,
    ZanixTemplateAttrs | undefined
  >(),
) => {
  preloadedDBTemplates = values
}
