import { expandGlobSync } from '@std/fs/expand-glob'
import { dirname, join, relative } from '@std/path'
import Handlebars from 'handlebars'

const HANDLEBARS_ROOT = 'src/modules/templates/handlebars'
const GENERATED_CODE_TEMPLATES_PATH = 'src/modules/templates/db/code-templates.generated.ts'

function templates() {
  // `{channel, name}` pairs discovered below, one per `.hbs` actually compiled — written out as
  // `CODE_TEMPLATES` once every template is processed (see `writeGeneratedCodeTemplates()`),
  // instead of being maintained by hand in `db/manifest.ts` (see `docs/templates.md`'s "Adding a
  // custom template" section).
  const discovered: { channel: string; name: string }[] = []

  const entries = [...expandGlobSync(`${HANDLEBARS_ROOT}/**/main.hbs`)].sort((a, b) =>
    a.path.localeCompare(b.path)
  )

  for (const { path } of entries) {
    const templateDir = dirname(path)
    const rawSource = Deno.readTextFileSync(path)
    const cssContent = Deno.readTextFileSync(join(templateDir, 'styles.css'))
    const compiled = Handlebars.precompile(rawSource)

    // `{channel}/{name}` relative to the handlebars root — exactly the pair `CODE_TEMPLATES`
    // needs, discovered here instead of hand-maintained.
    const [channel, name] = relative(HANDLEBARS_ROOT, templateDir).split('/')
    discovered.push({ channel, name })

    // The generated `main.js` below deliberately stays outside `@zanix/errors`' shared
    // hierarchy: it's a minimal leaf bundle emitted per template, not source that participates
    // in this package's own module graph. Its own `catch` still preserves the real ZodError as
    // `cause` (not just `e.message`) so the calling `notifications` code — which DOES have
    // `@zanix/errors` available — can inspect the real validation failure.
    Deno.writeTextFileSync(
      join(templateDir, 'main.js'),
      `// deno-coverage-ignore-file
/**
 * This file is autogenerated by a build or script process.
 * It has not been manually modified and should not be altered directly.
 * Any changes to the generated content should be made through the
 * corresponding source files or template configurations.
 */
import Handlebars from "handlebars/runtime.js";
import TemplateDataSchema from './schema.ts'

const compiled = Handlebars.template(${compiled});

export default function(context) {
  try{
    const data = TemplateDataSchema.parse(context);
    data.styles.css = \`\\n${cssContent}\` + '\\n' + data.styles.css
    return compiled(data);
  } catch (e) {
    // Keeps the real ZodError as \`cause\` instead of flattening to just \`e.message\`.
    throw new Error(e.message, { cause: e })
  }
}

// Raw source, for database-sync seeding — see \`db/manifest.ts\`.
export const source = ${JSON.stringify(rawSource)};
export const styles = ${JSON.stringify(cssContent)};
`,
    )
  }

  writeGeneratedCodeTemplates(discovered)
}

/**
 * Writes `db/code-templates.generated.ts`'s `CODE_TEMPLATES` from every `{channel, name}`
 * discovered above — sorted for a stable diff regardless of glob order.
 */
function writeGeneratedCodeTemplates(
  entries: { channel: string; name: string }[],
): void {
  const sorted = [...entries].sort((a, b) =>
    `${a.channel}:${a.name}`.localeCompare(`${b.channel}:${b.name}`)
  )
  const body = sorted.map(({ channel, name }) => `  { channel: '${channel}', name: '${name}' },`)
    .join('\n')

  Deno.writeTextFileSync(
    GENERATED_CODE_TEMPLATES_PATH,
    `// deno-coverage-ignore-file
/**
 * This file is autogenerated by \`deno task build-handlebars\` (see \`handlebars/compiler.ts\`).
 * It has not been manually modified and should not be altered directly — add a new base
 * template's \`.hbs\`/\`schema.ts\`/\`styles.css\` under \`handlebars/{channel}/{name}/\` and rerun
 * the build task instead (see \`docs/templates.md\`'s "Adding a custom template" section).
 */
import type { Notifiers } from 'typings/general.ts'

/**
 * The full list of \`{channel, name}\` pairs that own a real \`.hbs\` file in source
 * (\`handlebars/{channel}/{name}/\`) — the only templates a database sync can seed from or resync
 * against. Discovered directly from which \`main.hbs\` files exist, not maintained by hand.
 */
export const CODE_TEMPLATES: ReadonlyArray<{ channel: Notifiers; name: string }> = [
${body}
]
`,
  )
}

templates()
