import gulp from 'npm:gulp@^5.0.1'
import handlebars from 'npm:gulp-handlebars@^5.0.2'
import rename from 'npm:gulp-rename@^2.1.0'
import wrap from 'npm:gulp-wrap@^0.15.0'
import { dirname, join } from '@std/path'

function templates() {
  return gulp.src('src/modules/templates/handlebars/**/*.hbs', { base: './' })
    .pipe(handlebars())
    .pipe(
      wrap(function ({ file, contents }: { file: { path: string }; contents: ArrayBuffer }) {
        const templateDir = dirname(file.path)
        const cssContent = Deno.readTextFileSync(join(templateDir, 'styles.css'))
        // Read the original `.hbs` by its known, fixed filename rather than `file.path` itself —
        // by the time this callback runs, `file.path` may already reflect `rename()`'s `.js`
        // extension (`rename()` is declared after `wrap()` in the pipe chain, but gulp's stream
        // processing doesn't guarantee that ordering holds for a given vinyl file's `.path` by the
        // time this callback fires). Its raw text is what a database sync seeds `ZanixTemplate.hbs`
        // with, since the `compiled` bytecode above can't be used for that (see `docs/templates.md`).
        const rawSource = Deno.readTextFileSync(join(templateDir, 'main.hbs'))

        return `// deno-coverage-ignore-file
/**
 * This file is autogenerated by a build or script process.
 * It has not been manually modified and should not be altered directly.
 * Any changes to the generated content should be made through the
 * corresponding source files or template configurations.
 */
import Handlebars from "handlebars/runtime.js";
import TemplateDataSchema from './schema.ts'

const compiled = Handlebars.template(${contents.toString()});

export default function(context) {
  try{
    const data = TemplateDataSchema.parse(context);
    data.styles.css = \`\\n${cssContent}\` + '\\n' + data.styles.css
    return compiled(data);
  } catch (e) {
    throw new Error(e.message)
  }
}

// Raw source, for database-sync seeding — see \`db/manifest.ts\`.
export const source = ${JSON.stringify(rawSource)};
export const styles = ${JSON.stringify(cssContent)};
    `
      }),
    )
    .pipe(rename({ extname: '.js' }))
    .pipe(gulp.dest('./'))
}

templates()
