import gulp from 'npm:gulp@^5.0.1'
import handlebars from 'npm:gulp-handlebars@^5.0.2'
import rename from 'npm:gulp-rename@^2.1.0'
import wrap from 'npm:gulp-wrap@^0.15.0'
import { dirname, join } from '@std/path'

function templates() {
  return gulp.src('src/modules/templates/handlebars/**/*.hbs', { base: './' })
    .pipe(handlebars())
    .pipe(
      wrap(function ({ file, contents }: { file: { path: string }; contents: ArrayBuffer }) {
        const cssContent = Deno.readTextFileSync(join(dirname(file.path), 'styles.css'))

        return `/**
 * This file is autogenerated by a build or script process.
 * It has not been manually modified and should not be altered directly.
 * Any changes to the generated content should be made through the 
 * corresponding source files or template configurations.
 */
import Handlebars from "handlebars/runtime.js";
import TemplateDataSchema from './schema.ts'

const compiled = Handlebars.template(${contents.toString()});

export default function(context) {
  try{
    const data = TemplateDataSchema.parse(context);
    data.styles.css = \`\\n${cssContent}\` + '\\n' + data.styles.css
    return compiled(data);
  } catch (e) {
    throw new Error(e.message)
  } 
}
    `
      }),
    )
    .pipe(rename({ extname: '.js' }))
    .pipe(gulp.dest('./'))
}

templates()
